# superuser permission access
sudo : required
# telling travis we want docker so it installs 
services : 
  - docker

# steps that need to occur before testing or deploying
before_install :
  - docker build -t pradyumnarutvik/docker-react -f Dockerfile.dev .

# script section contains cmnds needed to test
script : 
  - docker run -e CI=true pradyumnarutvik/docker-react npm run test

# how to deploy
deploy :
  provider : elasticbeanstalk
# http://frontend-env.eba-qumrpm3a.eu-north-1.elasticbeanstalk.com/
  region : "eu-north-1"
# name of app
  app : "frontend"
  env : "Frontend-env"
  bucket_name : "elasticbeanstalk-eu-north-1-654654430800"
  bucket_path : "frontend"
  on : 
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : "$AWS_SECRET_KEY"
